core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('messageboard.urls')),
]

messageboard/urls.py
from django.urls import path

from .views import messageboard_list_view, messageboard_detail_view, messageboard_comment_to_message_view

app_name = 'messageboard'

urlpatterns = [
    path('comment/<int:pk>/', messageboard_comment_to_message_view, name='comment'),
    path('<int:pk>/', messageboard_detail_view, name='detail'),
    path('', messageboard_list_view, name='list'),
]

messageboard/models.py
from django.db import models


class Message(models.Model):
    message = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message


class Comment(models.Model):
    comment = models.CharField(max_length=250)
    message = models.ForeignKey(
        Message, on_delete=models.CASCADE, related_name='comments')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

messageboard/forms.py
# messageboard/forms.py

from django import forms

from .models import Comment, Message


class MessageboardForm(forms.ModelForm):
    nickname = forms.CharField(
        max_length=100, label='ニックネーム', initial='unknown')

    class Meta:
        model = Message
        fields = (
            'message',
        )
        labels = {
            'message': 'メッセージ',
        }
        widgets = {
            'message': forms.Textarea,
        }

    def clean_message(self):
        message = self.cleaned_data.get('message')
        if 'test' in message:
            raise forms.ValidationError('testという文言は含められません')
        return message


# class MessageboardForm(forms.Form):
#     message = forms.CharField(
#         max_length=240,
#         label='メッセージ',
#         widget=forms.Textarea(
#             attrs={'class': 'uk-textarea', 'placeholder': '240文字いないで入力'},
#         ))
#     nickname = forms.CharField(
#         max_length=100,
#         label='ニックネーム',
#         widget=forms.TextInput(
#             attrs={'class': 'uk-input', 'placeholder': '表示される名前'},
#         ))


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'comment',
        )

    def clean_comment(self):
        comment = self.cleaned_data.get('comment')
        ng_words = ["ばか", "バカ", "あほ", "アホ"]
        for ng_word in ng_words:
            if ng_word in comment:
                raise forms.ValidationError(f'{ng_word}という文言は含められません')
        return comment

messageboard/views.py
# messageboard/views.py

from django.shortcuts import redirect, render, get_object_or_404

from .forms import MessageboardForm, CommentForm
from .models import Message


def messageboard_list_view(request):
    """
    一覧を表示するview
    """
    form = MessageboardForm(request.POST or None)
    if form.is_valid():
        obj = form.save(commit=False)
        obj.message = f"{form.cleaned_data.get('message')} - by.{form.cleaned_data.get('nickname')}"
        obj.save()
        form = MessageboardForm()

    queryset = Message.objects.all()  # 全てのデータを取得する
    context = {
        'object_list': queryset,
        'form': form,
    }
    template_name = 'messageboard/list.html'
    return render(request, template_name, context)


def messageboard_detail_view(request, pk):
    """
    詳細を表示するview
    """
    obj = get_object_or_404(Message, id=pk)
    form = CommentForm()
    comments = obj.comments.all()
    context = {
        'object': obj,
        'form': form,
        'comments': comments,
    }
    template_name = 'messageboard/detail.html'
    return render(request, template_name, context)


def messageboard_comment_to_message_view(request, pk):
    comment_form = CommentForm(request.POST, None)
    if comment_form.is_valid():
        message_obj = get_object_or_404(Message, pk=pk)
        # 情報を追加するために保存を一時停止
        comment_obj = comment_form.save(commit=False)
        # コメントをしているメッセージを紐付ける
        comment_obj.message = message_obj
        # コメントを保存
        comment_obj.save()
        # コメントの保存が終わったらメッセージ画面へリダイレクト。
        # しかし、これはGET、POST処理に構わず行われるのでここで別途リダイレクトしなくてもif文の外でリダイレクトしてくれる
        # return redirect('messageboard:detail', pk=pk)
    # このviewにgetで直接アクセスされた場合、もしくはFormが不正の場合はメッセージに直接戻る
    return redirect('messageboard:detail', pk=pk)

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/css/uikit.min.css" />
    <title>Message Board</title>
    {% block styles %}
    {% endblock styles %}
</head>
<body>
    <h1 class="uk-heading-divider"><a class="uk-link-reset" href="{% url 'messageboard:list' %}">Message Board</a></h1>

    <div class="uk-container">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.5.7/dist/js/uikit-icons.min.js"></script>
</body>
</html>

templates/messageboard/detail.html
<!-- templates/messageboard/detail.html -->

{% extends '_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock styles %}

{% block content %}
<h3>Detail</h3>
<div id="home" class="uk-grid-divider uk-flex-center" uk-grid>
    <div class="article-filter uk-width-1-2@m">
        <div class="post-it">
            <p>{{ object.message }}</p>
        </div>
    </div>

    <div class="article-filter uk-width-1-2@m">
        <form action="{% url 'messageboard:comment' pk=object.id %}" method="post">
            {% csrf_token %}
            <p>{{ form.comment.label }}</p>
            <div class="uk-flex">
                {{ form.comment | add_class:"uk-input" }}
                <button class="uk-button uk-button-primary uk-margin-left" type="submit">comment</button>
            </div>
        </form>

        <ul class="uk-list">
            {% for comment in comments %}
                <div class="post-it-small">{{ comment.comment }}</div>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock content %}

templates/messageboard/list.html
<!-- templates/messageboard/list.html -->

{% extends '_base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/list.css' %}">
{% endblock styles %}

{% block content %}
{% for field in form %}
    {% if field.errors %}
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-alert></a>
            {{ field.errors }}
        </div>
    {% endif %}
{% endfor %}

<!-- This is a button toggling the modal -->
<button class="uk-button uk-button-default uk-margin-small-right" type="button" uk-toggle="target: #modal-example">Add</button>
<!-- This is the modal -->
<div id="modal-example" uk-modal>
    <div class="uk-modal-dialog uk-modal-body">
        <form action="." method="post">
            {% csrf_token %}
            {{ form.message.label }}
            {{ form.message | add_class:"uk-textarea" | attr:"placeholder:240 letters only" }}
            {{ form.nickname.label }}
            {{ form.nickname | add_class:"uk-input" | attr:"placeholder:displays to other users" }}
            <div class="uk-flex uk-flex-between">
                <button class="uk-button uk-button-danger uk-modal-close" type="button">Cancel</button>
                <button class="uk-button main-theme" type="submit">Add Message</button>
            </div>
        </form>
    </div>
</div>

<div class="ul-list uk-margin-top uk-child-width-1-3@s uk-grid-match" uk-grid>
    {% for message in object_list %}
        <div>
            <a class="uk-display-block uk-link-reset uk-padding-remove" href="{% url "messageboard:detail" pk=message.pk %}">
                <div class="post-it">
                    <p>{{ message.message }}</p>
                </div>
            </a>
        </div>
    {% endfor %}
</div>
{% endblock content %}